### Object creation in pandas

In [8]:
import pandas as pd

1. Using list of dictionaries to create a DataFrame:

In [9]:
lst = [{"C1": 1, "C2": 2}, {"C1": 3, "C2": 4}]
data = pd.DataFrame(lst, index=["R1", "R2"])
data

    C1  C2
R1   1   2
R2   3   4

2. Using Dictionaries to craete a dataframe

In [11]:
dc = {"C1": ["1", "3"],
        "C2": ["2","4"]}
data = pd.DataFrame(dc, index = ["R1", "R2"])
data

   C1 C2
R1  1  2
R2  3  4

3. Using list to create a dataframe

In [14]:
lst = [[52,32],[45,85]]
data = pd.DataFrame(lst, index = list('pq'), columns = list('ab'))
data

    a   b
p  52  32
q  45  85

4. Dataframe with heterogenous data types

In [15]:
df = pd.DataFrame({'A': [10., 20.],
                    'B': "text",
                    'C': [2,60],
                    'D': 3+9j})
print(df)
#       A     B   C       D
# 0  10.0  text   2  (3+9j)
# 1  20.0  text  60  (3+9j)
print(df.dtypes)
# A       float64
# B        object
# C         int64
# D    complex128
# dtype: object

      A     B   C         D
0  10.0  text   2  3.0+9.0j
1  20.0  text  60  3.0+9.0j
A       float64
B           str
C         int64
D    complex128
dtype: object

4. .info() method of dataframe ( DataFrameName.info() )

In [16]:
print(df.info())
# < class 'pandas.core.frame.DataFrame' >
# RangeIndex: 2 entries, 0 to 1
# Data columns (total 4 columns):
# A    2 non-null float64
# B    2 non-null object
# C    2 non-null int64
# D    2 non-null complex128
# dtypes: complex128(1), float64(1), int64(1), object(1)
# memory usage: 160.0+ bytes

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      float64
 1   B       2 non-null      str
 2   C       2 non-null      int64
 3   D       2 non-null      complex128
dtypes: complex128(1), float64(1), int64(1), str(1)
memory usage: 212.0 bytes
None

5. other methods for dataframe

In [17]:
print((df.index))   #index of rows
# RangeIndex(start=0, stop=2, step=1)
print(df.columns)   # index of columns
# Index(['A', 'B', 'C', 'D'], dtype='object')
print(df.values)    # display values of df
# [[10.0 'text' 2 (3+9j)]
#  [20.0 'text' 60 (3+9j)]]

RangeIndex(start=0, stop=2, step=1)
Index(['A', 'B', 'C', 'D'], dtype='str')
[[10.0 'text' 2 (3+9j)]
 [20.0 'text' 60 (3+9j)]]